version: '3'

services:

  web:
    build:
      context: ./dockerfiles/django_docker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000


  postgres:
    container_name: postgresql-db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB_NAME}


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:  
      - postgres


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    # volumes:
    #   - redisdata:/data
  
  
  celery:
    build:
      context: ./dockerfiles/celery_docker
      dockerfile: Dockerfile
    depends_on:
      - web
      - redis # або rabbitmq
    env_file:
      - .env
    command: celery -A proj worker -l INFO && celery-beat proj

# Optionally, define network configurations
# networks:
#   my_network:
#     driver: bridge